[package]
name = "geopattern"
version = "0.1.0"
authors = ["Alan Hoffmeister <alanhoffmeister@gmail.com>"]

[dependencies]
iron = "0.6.0"
geopattern = "0.2.0"
router = "0.6.0"
resvg = { version = "0.4.0", features = ["cairo-backend"] }
